# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test213400005():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_213400005(self):
    self.driver.get("https://www.globalsqa.com/angularJs-protractor/BankingProject/")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lg:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-valid").send_keys("Sabbir")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").send_keys("Hossain")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-pristine").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-untouched").send_keys("1204")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    assert self.driver.switch_to.alert.text == "Please check the details. Customer may be duplicate."
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lg:nth-child(3)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".marTop")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".marTop")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".marTop")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    self.driver.find_element(By.ID, "userSelect").click()
    dropdown = self.driver.find_element(By.ID, "userSelect")
    dropdown.find_element(By.XPATH, "//option[. = 'Sabbir Hossain']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-binding:nth-child(7)").click()
    self.driver.find_element(By.ID, "currency").click()
    dropdown = self.driver.find_element(By.ID, "currency")
    dropdown.find_element(By.XPATH, "//option[. = 'Dollar']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#currency > option:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-dirty > button").click()
    assert self.driver.switch_to.alert.text == "Account created successfully with account Number :1018"
    self.driver.find_element(By.CSS_SELECTOR, ".home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".center:nth-child(1) > .btn").click()
    self.driver.find_element(By.ID, "userSelect").click()
    dropdown = self.driver.find_element(By.ID, "userSelect")
    dropdown.find_element(By.XPATH, "//option[. = 'Sabbir Hossain']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-binding:nth-child(7)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-default")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys("50")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lg:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys("10")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lg:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fixedTopBox > .btn:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".center:nth-child(3) > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lg:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lg:nth-child(3)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-lg:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".marTop")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".marTop")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".marTop")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
